REQUIRE_FILE_LIST =  '%__REQUIRE_FILE_LIST%' #require file list
END_CONNECT = '%__END_CONNECT%' #結束連線
SET_SEARCH_TYPE = '%__SET_SEARCH_TYPE%' #[1]搜尋檔案 [2]搜尋資料夾
SET_PATTERN_KEY = '%__SET_PATTERN_KEY%' #搜尋條件
SEARCH_TARGET = '%__SEARCH_TARGET%' #開始搜尋目標
SELECT_TARGETS = '%__SELECT_TARGETS%' #選擇目標
SET_MAIL_RECVER = '%__SET_MAIL_RECVER%' #郵件寄送對象